---
abstract: 'Override client IP with header value provided by proxy/load balancer'
author:
  - 'Sherwin Daganato <sherwin@daganato.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-RealIP
no_index:
  directory:
    - t
    - inc
requires:
  Net::Netmask: 0
  Plack: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/sherwind/Plack-Middleware-RealIP/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/sherwind/Plack-Middleware-RealIP.git
version: 0.02
